//! doc url: <https://open.feishu.cn/document{{ fullPath }}>
// Code generated by gen_api. DO NOT EDIT.

use serde::{Deserialize, Serialize};

use crate::api::BaseResp;
use crate::api::HasBaseResp;
use crate::core::model::{
    ApiRequest, CommonResponse, MethodOption, ReqParam, StreamReqData, StreamReqParam,
};
use crate::{
    core::{http_client::HttpClient, store::Store},
    error::Error,
};

use crate::api::gen::{{ service_snake_case }}::{{ serviceUpperCamelCase  }}Service;

impl<'c, IStore: Store, IClient: HttpClient>
    {{ serviceUpperCamelCase  }}Service<'c, IStore, IClient>
{
    /// **api 版本: {{ update_time }}**
    ///
    {{ description }}
    ///
    {{ tips }}
    ///
    /// doc: <https://open.feishu.cn/document{{ fullPath }}>
    ///
    /// new doc: <https://open.feishu.cn{{ doc_path }}>
    /// 
    /// api url: <{{ api_url }}>
    pub async fn {{ func_name }}<Data: StreamReqData>(
        &self,
        req: {{ req_type }}<Data>,
    ) -> Result<({{ resp_type }}, CommonResponse), Error> {
        self.{{ func_name }}_with_opt(req, Default::default()).await
    }

    /// 参见 [{{ func_name }}](#method.{{ func_name }}) 函数
    pub async fn {{ func_name }}_with_opt<Data: StreamReqData>(
        &self,
        req:  {{ req_type }}<Data>,
        method_option: MethodOption,
    ) -> Result<({{ resp_type }}, CommonResponse), Error> {
        #[cfg(feature = "test-util")]
        {
            if let Some(f) = self.mock().get_mock_{{ func_name }}(&req) {
                tracing::info!("[lark] {{ serviceUpperCamelCase  }}#{{ UpperCamelFunc }} **mocking** api");
                return f(req);
            }
        }

        tracing::info!("[lark] {{ serviceUpperCamelCase }}#{{ UpperCamelFunc }} call api");

        let req = ApiRequest::<()> {
            scope: "{{ serviceUpperCamelCase  }}",
            api: "{{ UpperCamelFunc }}",
            method: {{ method }},
            url: String::new() + self.cli.open_base_url.as_ref() + "{{ path }}",
            stream_param_data: req.gen_stream_param(),
            method_option,
            {{ auth }}
            ..Default::default()
        };

        let (resp, common_resp): ({{ resp_type }}Inner, _) = self.cli.do_req(req).await?;
        let data = match resp.data {
            Some(data) => data,
            None => {
                return Err(Error::ErrResponse(anyhow::anyhow!("missing response data"), common_resp));
            }
        };
        Ok((data, common_resp))
    }
}

#[derive(Debug, lark_bot_sdk_macros::ApiReqParams)]
pub struct {{ req_type }}<Data: StreamReqData> {
    {{ req_fields_path }}
    {{ req_fields_query }}
    {{ req_fields_stream }}
    #[api(kind = "stream", name = "#data#", option = "false")]
    pub data: Data,
}

#[derive(Debug, Serialize, Deserialize, Clone, lark_bot_sdk_macros::ApiBaseResp)]
struct {{ resp_type }}Inner {
    #[serde(flatten)]
    data: Option<{{ resp_type }}>,
    #[serde(flatten)]
    base: BaseResp,
}

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct {{ resp_type }} {
    {{ resp_fields }}
}

{{ resp_fields_sub_type }}

#[cfg(feature = "test-util")]
mod test_utils {
    use std::sync::Arc;

    use self::gen::{ {{ service_snake_case }}::{{ serviceUpperCamelCase  }}ServiceMocker};
    use crate::core::mocker::*;

    use super::*;
    use crate::api::*;
    use crate::core::model::*;

    pub struct Mocker;

        pub trait MockFunc<D: StreamReqData>:
        Fn({{ req_type }}<D>) -> Result<({{ resp_type }}, CommonResponse), Error>
        + Send
        + Sync
        + 'static
    {
    }
    impl<
            D: StreamReqData,
            T: Fn({{ req_type }}<D>) -> Result<({{ resp_type }}, CommonResponse), Error>
                + Send
                + Sync
                + 'static,
        > MockFunc<D> for T
    {
    }

    impl<'c, IStore: Store, IClient: HttpClient>
        {{ serviceUpperCamelCase  }}ServiceMocker<'c, IStore, IClient>
    {
        pub fn mock_{{ func_name }}<T: StreamReqData, F: MockFunc<T>>(
            &self,
            f: F,
        ) -> MockerBuilder<Mocker, {{ req_type }}<T>, {{ resp_type }}, Arc<dyn MockFunc<T>>> {
            MockerBuilder::new(self.cli.instance_id, Arc::new(f))
        }

        pub(super) fn get_mock_{{ func_name }}<T: StreamReqData>(
            &self,
            req: &{{ req_type }}<T>,
        ) -> Option<Arc<dyn MockFunc<T>>> {
            do_mock::<Mocker, {{ req_type }}<T>, {{ resp_type }}, Arc<dyn MockFunc<T>>>(
                self.cli.instance_id,
                req,
            )
        }
    }
}
